name: Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # https://github.com/actions/checkout/releases/tag/v4.1.1

    - name: Set up Python
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236  # https://github.com/actions/setup-python/releases/tag/v4.7.1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install

    - name: Run linters
      run: |
        poetry run black --check .
        poetry run isort --check-only .
        poetry run flake8 .
        poetry run mypy .

    - name: Run tests
      run: |
        poetry run pytest